### ISSUE TITLE
Warning: Undefined array key "subpalettes"

### ISSUE THREAD

**Issue by drum-und-dran** [ContaoMonitoring/monitoring-scan-client#5]
Hi Cliff, hi Kirsten, 
**It's great how reliably the extension is still running** - almost at least - **unbelievable**!

If the Contao debug mode is activated and you want to edit a monitoring entry in the backend, the above error message occurs. 
Without debug mode, the following error appears: 
`502 Bad Gateway - nginx`

Would it be possible for you to take a look at the problem? 

_System: Contao 4.12.4, PHP 8.0.13_ 

Thanks very much,
Gunnar

**Comment by cliffparnitzky** [comment]
Right now this seems to be a probleme with Contao 4.12.4 and/or PHP 8.0.13.

I cannot reproduce it in my environment with Contao 4.9 and PHP 7.4.

@wugu Can you downgrade you system to the same environment as mine and test it?

**Comment by drum-und-dran** [comment]
I think it's a problem with actual environment too (PHP7.4 is no longer in active support – since 28 Nov 2021). 

@cliffparnitzky Downgrade is not possible at the moment, the following error is occur:
`Could not delete ***snip***/var/cache/prod/doctrine/orm/Proxies/__CG__ContaoCoreBundleEntityCrawlQueue.php`

That's why I only tested whether a temporary downgrade would be possible. I don't need a productive downgrade.
It would be great if the extension could be updated.

**Comment by cliffparnitzky** [comment]
As I mentioned, I have no problems with my environment. You described an error, that seems to accure 4.12.4 and/or PHP 8.0.13.

We will upgrade the extension to PHP 8, when it is necessary. But generally we have enouph time, because PHP 7.4 is security supported sind Nov 2022.

If there is time and budget we will take care.

**Comment by drum-und-dran** [comment]
Ok, thanks a lot.
